# Generated by Django 5.2.1 on 2025-05-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_userprofile_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('georgia', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
