# Generated by Django 5.2.1 on 2025-05-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
